package model;

public enum DeckFormat {
    STANDARD, BOOSTER_DRAFT, SEALED_DECK, BLOCK,
    MODERN, COMMANDER, LEGACY, VINTAGE, TEAM_UNIFIED_CONSTRUCTED,
    CONSPIRACY, TEAM_BOOSTER_DRAFT, TEAM_SEALED_DECK,
    FREEFORM, MOMIR, PAUPER, PLANESWALKER, DUELS,
    CUSTOM, BOOSTER_HANDOVER
}